@host = http://localhost:4400

###

GET {{host}}/api/pets

###

POST {{host}}/api/pets
Content-Type: application/json

{"name": "Fluffy", "age": 5, "weightInKg": 7}

###

GET {{host}}/api/owners

###

POST  {{host}}/api/owners
Content-Type: application/json

{"name":"Viola", "age":30}